# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - exhaustruct # pointless
    - err113 # no need to wrap all errors, too much work
    - depguard # breaking things: https://github.com/atc0005/go-ci/issues/1024
    - gochecknoglobals # globals are sometimes ok
    - testpackage # todo: consider enabling
    - tenv # replaced by usetesting

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  goconst:
    min-occurrences: 5
    ignore-tests: true
