version: "2"
linters:
  default: all
  disable:
    - depguard # breaking things: https://github.com/atc0005/go-ci/issues/1024
    - err113 # no need to wrap all errors, too much work
    - exhaustruct # pointless
    - gochecknoglobals # globals are sometimes ok
    - testpackage # todo: consider enabling
    - wsl # deprecated
    - noinlineerr # big fan of inline errors
  settings:
    goconst:
      min-occurrences: 5
    varnamelen:
      min-name-length: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    golines:
      max-len: 120
