version: "3"

tasks:
  fmt:
    desc: format code
    vars:
      MODULE:
        sh: head -n 1 go.mod | cut -d' ' -f2
    cmds:
      - go mod tidy
      - go fix ./...
      - golangci-lint run --fix ./...
      - golangci-lint fmt ./...
      - shfmt -l -i 2 -ci -sr -w .

  lint:
    desc: lint code
    cmds:
      - go mod tidy --diff
      - golangci-lint run ./...
      - helm lint internal/helm/pv-migrate
      - shfmt -l -i 2 -ci -sr .

  clean:
    desc: clean
    cmds:
      - rm -rf {{.ROOT_DIR}}/dist/

  update-docs:
    desc: update generated docs
    cmds:
      - task: update-cli-reference
      - task: update-helm-chart-docs

  update-cli-reference:
    desc: update generated CLI reference
    env:
      ROOT_USAGE:
        sh: go run ./cmd/pv-migrate --help
      BACKUP_USAGE:
        sh: go run ./cmd/pv-migrate backup --help
      RESTORE_USAGE:
        sh: go run ./cmd/pv-migrate restore --help
      STATUS_USAGE:
        sh: go run ./cmd/pv-migrate status --help
      CLEANUP_USAGE:
        sh: go run ./cmd/pv-migrate cleanup --help
      COMPLETION_USAGE:
        sh: go run ./cmd/pv-migrate completion --help
    cmds:
      - mkdir -p {{.ROOT_DIR}}/docs
      - >-
        docker run --rm -v {{.ROOT_DIR}}:/project
        -e ROOT_USAGE -e BACKUP_USAGE -e RESTORE_USAGE -e STATUS_USAGE -e CLEANUP_USAGE -e COMPLETION_USAGE
        hairyhenderson/gomplate:stable
        --file /project/docs/cli-reference.md.gotmpl
        --out /project/docs/cli-reference.md

  update-helm-chart-docs:
    desc: update helm chart docs
    vars:
      # renovate: depName=norwoodj/helm-docs datasource=github-releases
      HELM_DOCS_VERSION: v1.14.2
    cmd: >-
        docker run --rm -v {{.ROOT_DIR}}:/helm-docs
        jnorwood/helm-docs:{{.HELM_DOCS_VERSION}}
        --chart-search-root /helm-docs/internal/helm

  build:
    desc: build
    cmds:
      - goreleaser build --snapshot --rm-dist --single-target

  release:
    desc: release
    vars:
      NUM_LAST_TAGS: 3
      LAST_TAGS:
        sh: git tag --sort=-version:refname | head -n {{.NUM_LAST_TAGS}} | xargs echo
      NEXT_TAG:
        sh: svu next
    cmds:
      - "echo Last {{.NUM_LAST_TAGS}} tags: {{.LAST_TAGS}}"
      - "echo Next tag: {{.NEXT_TAG}}"
      - git tag -a {{.NEXT_TAG}} -m "Release {{.NEXT_TAG}}"
      - git push origin {{.NEXT_TAG}}
