{{- if .Values.rclone.enabled -}}
{{- if .Values.rclone.configMount -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pv-migrate.fullname" . }}-rclone
  namespace: {{ .Values.rclone.namespace }}
  labels:
    app.kubernetes.io/component: rclone
    {{- include "pv-migrate.labels" . | nindent 4 }}
data:
  rclone.conf: {{ (required "rclone.config is required!" .Values.rclone.config) | b64enc | quote }}
type: Opaque
{{- end }}
{{- end }}
