# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PvMigrate < Formula
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"
  version "0.5.4"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.5.4/pv-migrate_0.5.4_darwin_x86_64.tar.gz"
    sha256 "a65da4f2394b7ade152640d03534cf0a5f657fa7b8512e8e54361ea5f08eeefe"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.5.4/pv-migrate_0.5.4_linux_x86_64.tar.gz"
    sha256 "61abce69b11bebc76f92964db2094bba52053fb91bbec04699bdc338d0556627"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.5.4/pv-migrate_0.5.4_linux_arm64.tar.gz"
    sha256 "b719dcc1798a9bcbaa80443b98f3a37eb0f0d618c980466891e948f04d893ca9"
  end

  def install
    bin.install "pv-migrate"
  end

  test do
    system "#{bin}/pv-migrate -v"
  end
end
