{{- if .Values.sshd.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pv-migrate.fullname" . }}-sshd
  namespace: {{ .Values.sshd.namespace }}
  labels:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.labels" . | nindent 4 }}
  {{- with .Values.sshd.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.sshd.service.type }}
  {{- with .Values.sshd.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.sshd.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/component: sshd
    {{- include "pv-migrate.selectorLabels" . | nindent 4 }}
{{- end }}
