name: build

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - renovate/**
    paths-ignore:
      - "**.md"
      - "img/**"
      - "test/**"
      - ".gitignore"
      - "renovate.json"
      - ".krew.yaml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "img/**"
      - "test/**"
      - ".gitignore"
      - "renovate.json"
      - ".krew.yaml"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euox pipefail {0}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          # renovate: depName=go-task/task datasource=github-releases
          version: 3.49.1
      - name: Tidy go.mod
        run: go mod tidy
      - name: Run linters
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          # renovate: depName=golangci/golangci-lint datasource=github-releases
          version: v2.11.4
          args: --timeout=10m0s
          install-mode: goinstall
      - name: Build with Goreleaser
        if: ${{ always() }}
        uses: goreleaser/goreleaser-action@v7.0.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v2.14.3
          args: build --snapshot --clean --single-target
      - name: Update usage
        run: task update-usage
      - name: Update helm chart docs
        run: task update-helm-chart-docs
      - name: Check for dirty files
        run: git diff --exit-code
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Get short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build images
        run: |
          TAG="${{ steps.vars.outputs.sha }}"
          docker build -t integration-test-rsync:$TAG ./docker/rsync/
          docker build -t integration-test-sshd:$TAG ./docker/sshd/

      - name: Install go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
      - name: Install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Install cilium-cli
        env:
          # renovate: depName=cilium/cilium-cli datasource=github-releases
          CILIUM_CLI_VERSION: v0.19.2
        run: |
          wget https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-amd64.tar.gz
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
          rm cilium-linux-amd64.tar.gz

      - name: kind-1 - Setup
        uses: ./.github/actions/setup-cluster
        with:
          cluster_name: kind-1
          kubeconfig: /home/runner/.kube/config
          image_tag: ${{ steps.vars.outputs.sha }}
          metallb_ip_range_start: 240
          metallb_ip_range_end: 255

      - name: kind-2 - Setup
        uses: ./.github/actions/setup-cluster
        with:
          cluster_name: kind-2
          kubeconfig: /home/runner/.kube/kind-2.yaml
          image_tag: ${{ steps.vars.outputs.sha }}
          metallb_ip_range_start: 220
          metallb_ip_range_end: 235

      # 5. Run Tests
      - name: Run tests
        env:
          PVMIG_TEST_EXTRA_KUBECONFIG: /home/runner/.kube/kind-2.yaml
          # Pass only the image name:tag. Kind will find it locally.
          RSYNC_IMAGE: integration-test-rsync:${{ steps.vars.outputs.sha }}
          SSHD_IMAGE: integration-test-sshd:${{ steps.vars.outputs.sha }}
        run: go test -tags integration -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -timeout 20m -v ./...
      - name: Send coverage
        uses: codecov/codecov-action@v6.0.0
        with:
          files: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
